spring:
  application:
    name: note-api
  profiles:
    #配置文件 dev-开发环境  prod-生产环境
    active: dev
    #actice: prod
  #上传文件大小限制
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: x-key
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格    kik风格："gr_SwoIN0MC1ewxHX_vfCW3BothWDZMMtx__"
    token-style: tik
    # 是否输出操作日志
    is-log: true

#API通用前缀
server:
  servlet:
    context-path: /api/v1

